global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using Ardalis.Result;
global using KanbanBoard.Core.ContributorAggregate;
global using KanbanBoard.UseCases.Contributors.Create;
global using Shouldly;
global using Mediator;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
global using TaskStatus = KanbanBoard.Core.TaskAggregate.TaskStatus;
